import '@/styles/main.scss';

import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

import { ThemeProvider } from '@/client/providers/theme-provider';
import { TRPCReactProvider } from '@/client/providers/trpc-react-provider';
import { Toaster } from '@/components/ui/sonner';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`font-sans ${inter.variable}`}>
				<ClerkProvider>
					<TRPCReactProvider cookies={cookies().toString()}>
						<ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
							{children}
							<Toaster />
						</ThemeProvider>
					</TRPCReactProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
